## YAML Override template
## original/file.tpl: override/file.tpl
---
system/UsersModule/Resources/views/User/main.tpl: themes/PLTheme/Resources/views/modules/ZikulaUsersModule/User/main.tpl
system/ThemeModule/Resources/views/moduleheader.tpl: themes/PLTheme/Resources/views/modules/ZikulaThemeModule/moduleheader.tpl
